// Code generated by MockGen. DO NOT EDIT.
// Source: ./sync_client.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockSyncClient is a mock of SyncClient interface.
type MockSyncClient struct {
	ctrl     *gomock.Controller
	recorder *MockSyncClientMockRecorder
}

// MockSyncClientMockRecorder is the mock recorder for MockSyncClient.
type MockSyncClientMockRecorder struct {
	mock *MockSyncClient
}

// NewMockSyncClient creates a new mock instance.
func NewMockSyncClient(ctrl *gomock.Controller) *MockSyncClient {
	mock := &MockSyncClient{ctrl: ctrl}
	mock.recorder = &MockSyncClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSyncClient) EXPECT() *MockSyncClientMockRecorder {
	return m.recorder
}

// CheckBucketLocationConstraint mocks base method.
func (m *MockSyncClient) CheckBucketLocationConstraint(bucketName, bucketLocationConstraint string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckBucketLocationConstraint", bucketName, bucketLocationConstraint)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckBucketLocationConstraint indicates an expected call of CheckBucketLocationConstraint.
func (mr *MockSyncClientMockRecorder) CheckBucketLocationConstraint(bucketName, bucketLocationConstraint interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckBucketLocationConstraint", reflect.TypeOf((*MockSyncClient)(nil).CheckBucketLocationConstraint), bucketName, bucketLocationConstraint)
}

// CopyObjectToBucket mocks base method.
func (m *MockSyncClient) CopyObjectToBucket(srcBucketName, destBucketName, objectName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CopyObjectToBucket", srcBucketName, destBucketName, objectName)
	ret0, _ := ret[0].(error)
	return ret0
}

// CopyObjectToBucket indicates an expected call of CopyObjectToBucket.
func (mr *MockSyncClientMockRecorder) CopyObjectToBucket(srcBucketName, destBucketName, objectName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CopyObjectToBucket", reflect.TypeOf((*MockSyncClient)(nil).CopyObjectToBucket), srcBucketName, destBucketName, objectName)
}

// SelectObjects mocks base method.
func (m *MockSyncClient) SelectObjects(bucketName, regex string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectObjects", bucketName, regex)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectObjects indicates an expected call of SelectObjects.
func (mr *MockSyncClientMockRecorder) SelectObjects(bucketName, regex interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectObjects", reflect.TypeOf((*MockSyncClient)(nil).SelectObjects), bucketName, regex)
}
